[package]
name = "deadbeef"
version = "0.1.1"
edition = "2021"
publish = false
license = "GPL-3.0-or-later"

[dependencies]
clap = { version = "4", features = ["derive"] }
deadbeef-core = { version = "0.1.0", path = "../core" }
hex = "0.4"
num_cpus = "1"
